INSERT INTO ROLE (NAME) VALUES
    ('ROLE_AUTHENTICATED');
INSERT INTO ROLE (NAME) VALUES
    ('ROLE_ADMIN');

INSERT INTO USERS(EMAIL, PASSWORD) VALUES ('mail1@mail.com','$2a$10$IgPBrBNNOaCVhb4dGmEKLeMPndC09k30PbQq..kMghoDzZNYicVG6');
INSERT INTO USERS(EMAIL, PASSWORD) VALUES ('mail2@mail.com','$2a$10$E3fnG2Z/pNYdQCuMOSYCn.UyTLW1zXfCwR.ds5j9IztyJ0TIjRyJG');
INSERT INTO USER_ROLE (user_id, role_id) VALUES (1, 1);
INSERT INTO USER_ROLE (user_id, role_id) VALUES (2, 1);